name: Renovate
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - uses: renovatebot/github-action@v43.0.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          configurationFile: renovate.json5
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}